version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      "@typescript-eslint/*":
        patterns:
          - "@typescript-eslint/*"
      "@commitlint/*":
        patterns:
          - "@commitlint/*"
      "@react-router/*":
        patterns:
          - "@react-router/*"
      "@sentry/*":
        patterns:
          - "@sentry/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      datocms:
        patterns:
          - "datocms-structured-text-to-html-string"
          - "datocms-structured-text-to-plain-text"
          - "datocms-structured-text-utils"
          - "react-datocms"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
