import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// eslint-disable-next-line
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line
import * as build from '../build/server';

// eslint-disable-next-line
// @ts-ignore - the server build file is generated by `remix vite:build`
export const onRequest = createPagesFunctionHandler({ build });
