services:
  nginx:
    image: nginx:1.27-alpine
    container_name: com.wouterds--nginx
    mem_limit: 32mb
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wouterds
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.comwouterds.rule=Host(`wouterds.com`)"
      - "traefik.http.routers.comwouterds.entrypoints=websecure"
      - "traefik.http.routers.comwouterds.tls=true"
      - "traefik.http.routers.comwouterds-http.rule=Host(`wouterds.com`)"
      - "traefik.http.routers.comwouterds-http.entrypoints=web"
      - "traefik.http.routers.comwouterds-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

  node:
    image: ghcr.io/wouterds/wouterds.com
    mem_limit: 256mb
    container_name: com.wouterds--node
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
    networks:
      - mariadb
      - wouterds

  redis:
    image: redis:7.4-alpine
    mem_limit: 128mb
    container_name: com.wouterds--redis
    restart: unless-stopped
    networks:
      - wouterds

networks:
  proxy:
    external: true
  mariadb:
    external: true
  wouterds:
    name: wouterds
