name: deploy

on:
  push:
    branches: main
    paths: [src/**, package.json]
  pull_request:
    paths: [src/**, package.json]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://wouterds.be' || steps.deploy.outputs.deployment-url }}
    env:
      SENTRY_ORG: wouterds
      SENTRY_PROJECT: website
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DIST: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: sentry
        uses: getsentry/action-release@v1.7.0
        with:
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
          dist: ${{ github.sha }}
          ignore_missing: true
      - name: deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build/client --project-name=wouterds --branch=${{ github.ref == 'refs/heads/main' && 'main' || github.ref }}
