name: deploy

on:
  push:
    branches: main
    paths: [src/**, package.json]
  pull_request:
    paths: [src/**, package.json]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://wouterds.be' || steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./
          command: pages deploy ./public --project-name=wouterds --branch=${{ github.ref == 'refs/heads/main' && 'main' || github.ref }}
